### ISSUE TITLE
1.19.3 Support?

### ISSUE THREAD

**Issue by Calamity2112** [CyborgCabbage/emojitype#11]
Latest version of Minecraft (1.19.3) does not work with version 2.0.1+1.19

**Comment by xxxkingxl** [comment]
It sould be cool
its a nice mod do.

**Comment by xxxkingxl** [comment]
its 1 of the mods I`m waiting on to update, so I can add it to an updated modpack, this mod was in an older version of my modpack and i like to add it to the 1.19.3 version.
