### ISSUE TITLE
[Bug] [1.18.2] A small amount is only working + no autocomplete ( tab )

### ISSUE THREAD

**Issue by xR4YM0ND** [CyborgCabbage/emojitype#4]
Hey there, i have styled chat installed and emojitype as well 

when i try to type:

: 

nothing happens, no autocomplete, nothing. 

some emojis work ( bell & bow ) 

pickaxe, circle, axe, anchor ..... dont work 

I only installed it on the server

![2022-04-03_23 33 04](https://user-images.githubusercontent.com/97298005/161449574-17aff50b-4971-4b10-abb9-c65c2b293125.png)

[latest.log](https://github.com/CyborgCabbage/emojitype/files/8405549/latest.log)

**Comment by CyborgCabbage** [comment]
This is a client side mod, it doesn't do anything when installed on the server.
