### ISSUE TITLE
Crash on text fields with filter

### ISSUE THREAD

**Issue by AmberIsFrozen** [CyborgCabbage/emojitype#9]
On certain mods, there will be a filter applied to text fields to help limit what player can type.
Some mods uses the vanilla text field filter, while the others does their own processing and set the value to a processed one, but it doesn't matter in this case.

When you type the 1st character that does not match the filtering, that character will no longer exist, leave the text empty.
But presumably the mod is not expecting that the string would be empty after typing a character, then it just crashes at charAt.
(String index out of range: 0)
https://github.com/CyborgCabbage/emojitype/blob/ebc570e74e81e96190d6c5fc0d243ac02cfc9efd/src/main/java/cyborgcabbage/emojitype/emoji/EmojiCode.java#L25

### Crash Report
[crash-2022-09-19_21.43.07-client.txt](https://github.com/CyborgCabbage/emojitype/files/9599555/crash-2022-09-19_21.43.07-client.txt)

**Comment by CyborgCabbage** [comment]
I think I've fixed this in 2.0.1
